format = "$directory $all$git_branch$git_commit$git_state$git_status$character"
right_format = "$package$cmd_duration$sudo"
add_newline = false
command_timeout = 2000

[character]
success_symbol = "[󰏫 ](bright-green)" 
error_symbol = "[! ](bright-red)"
vimcmd_symbol = "[󰹇 ](cyan)"
# Only fish
# vimcmd_replace_one_symbol = "[ ](blue)" 
# vimcmd_replace_symbol = "[ ](blue)"

[sudo]
format = "[ 󰆥 ](bright-yellow)"
disabled = false

[directory]
truncation_length = 3
home_symbol = "󰋞 "
read_only = " "
format = "[$read_only](bright-yellow)[$path](bright-purple)"

[cmd_duration]
format = "[ 󰔟 $duration](bright-black)"

[package]
format = "[󰏗 $version](bright-black) "
disabled = false

[line_break]
disabled = false

[git_branch]
style = "bold bright-blue"

[git_state]
disabled = false

[git_status]
disabled = false
modified = ""
deleted = ""
renamed = ""
untracked = ""
staged = ""
conflicted = ""
style = "bright-black"
ahead = '󱦲${count}'
diverged = '⇕󱦲${ahead_count}󱦳${behind_count}'
behind = '󱦳${count}'

[git_commit]
disabled = false

[lua]
format = "via [ $version](bold blue) "

[dart]
format = "via [ $version](bold blue) "

[nodejs]
format = "via [ $version](bold green) "

[java]
format = "via [ $version](bold orange) "
